//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIKitTutorials.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestHistory
    {
        public int id { get; set; }
        public Nullable<System.DateTime> DateRequest { get; set; }
        public string TypeRequest { get; set; }
        public Nullable<int> idUser { get; set; }
        public string LoginUser { get; set; }
    
        public virtual User User { get; set; }
    }
}
