//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIKitTutorials.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestGroup
    {
        public int id { get; set; }
        public Nullable<System.DateTime> DateRequest { get; set; }
        public string LoginGroup { get; set; }
        public string idGroup { get; set; }
        public Nullable<int> MembersCount { get; set; }
        public string JsonFile { get; set; }
    }
}
